[package]
name = "fontconfig-sys"
version = "0.0.0"
edition = "2021"

[dependencies]
ffi-utils = { path = "../ffi-utils" }
libc = "0.2.126"

[build-dependencies]
bindgen = "0.59.2"
pkg-config = "0.3.25"
