[package]
name = "figma-agent"
version = "0.0.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.1"
actix-web = "4.0.1"
env_logger = "0.9.0"
fontconfig = { path = "../fontconfig" }
freetype = { path = "../freetype" }
itertools = "0.10.3"
lazy_static = "1.4.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
xdg = "2.4.1"
