[package]
name = "figma-agent"
version = "0.0.0"
edition = "2021"

[dependencies]
fontconfig = { path = "../fontconfig" }
form_urlencoded = "1.0.1"
freetype = { path = "../freetype" }
itertools = "0.10.3"
serde_json = "1.0.81"
tiny_http = "0.11.0"
uriparse = "0.6.4"
