name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install libfreetype6-dev libfontconfig1-dev

      - run: cargo clippy -- --deny warnings
      - run: cargo fmt --check
